#!/bin/sh
trap '' 0 1 2 9 15

nrad=_
ncopy=_
for (( i=0; i < $nrad; i++ ))
do
	for (( j=0; j < ${ncopy}; j++ ))
	do
	a="ini_files/cav_npt_";
	b="dumps_end/dump_end_"
	c=".txt"
	d="_"

	file=$a$i$d$j;
	file2=$b$i$d$j$c
	if ! [ -f "$file2" ]; then
	sbatch -n32 -t40 -i $file --wrap='srun lammps_16_03_2018';
	echo "$i";
	fi
	done;
done;