#!/bin/sh
trap '' 0 1 2 9 15

nrad=_
ncopy=_
for (( i=0; i<$nrad; i++ ))
do
	for (( j=0; j<$ncopy; j++ ))
	do	
		a="sbatch -n 1 -t 120 --wrap='srun ./calcV "
		b="'"
		c=" " 
		d=$a$i$c$j$b
		e="results/result_"
		f="_"
		g=".txt"
		file_result=$e$i$f$j$g
		if ! [ -f "$file_result" ]; then
			echo "$d" >> temp
		fi
	done;
done;

chmod 777 temp
./temp
rm temp

