#!/bin/sh
trap '' 0 1 2 9 15

N=50
for (( i=0; i <= $N; i++ ))
do
a="in_files/in.l-";
b="dumpL/dump_liquid_"
c=".txt"
file=$a$i;
file2=$b$i$c
if ! [ -f "$file2" ]; then
sbatch -n32 -t 180 -i $file --wrap='srun lammps_16_03_2018';
echo "$i";
fi
done;